// we should consider adding timeout to every stage (stage timeouts - good practice) in order to eliminate the problem of hanging Jenkins Pipeline and blocking executors forever
// we don't put timeout at the very beginning (global timeout)

pipeline {
	agent any   // use any available executor or workspace for this pipeline job
	stages {
  stage('Setup') {
    options {
      timeout(time: 2, unit:"MINUTES")     // the timeout for this specific stage is 2 minutes
    }
    steps {
      sh '''echo "Setting up ..."
      mkdir webapp
      cp -p /var/lib/jenkins/workspace/rikiwebapp-pipeline/index.py webapp
      cp -p /var/lib/jenkins/workspace/rikiwebapp-pipeline/Dockerfile webapp'''
    }
  }

  stage('Test') {
    options {
      timeout(time: 2, unit:"MINUTES")     // the timeout for this specific stage is 2 minutes
    }
    steps {
      echo "Testing ..."
    }
  }

  stage('Deploy and Build') {
    steps {
      sshPublisher(publishers: [sshPublisherDesc(configName: 'docker-host-1', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: 'docker build -t rikiwebapp-image .; sleep 10; docker run -d --name rikiwebapp-container -p5000:80 rikiwebapp-image;', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '.', remoteDirectorySDF: false, removePrefix: 'webapp', sourceFiles: 'webapp/*')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
    }
  }

}

}